name: Frontend Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint eslint

      - name: Create stylelint config
        run: echo '{ "rules": { "block-no-empty": true, "color-no-invalid-hex": true } }' > .stylelintrc.json

      - name: Create eslint config
        run: echo '{ "env": { "browser": true, "es2021": true }, "extends": "eslint:recommended" }' > .eslintrc.json

      - name: Lint HTML
        run: htmlhint index.html

      - name: Lint CSS
        run: stylelint style.css

      - name: Lint JavaScript
        run: eslint script.js
