name: Run Simple Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run dummy test cases
        run: |
          echo "Running Test 1..."
          echo "✅ Test 1 passed"
          
          echo "Running Test 2..."
          echo "✅ Test 2 passed"
          
          echo "Running Test 3..."
          echo "✅ Test 3 passed"

      - name: All tests passed
        run: echo "🎉 All tests completed successfully!"
