name: Simple Workflow

on:
  push:
    branches:
      - main  # You can change this to your default branch name

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World!"
