name: "Basic Security Validation Workflow"

on:
  push:
    branches: ["main", "release/**"]
  pull_request:
    branches: ["main", "release/**"]
  workflow_dispatch:

jobs:
  html-security-checks:
    name: "HTML Security Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Check for inline scripts"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            if grep -q '<script>' "$f"; then
              echo "❌ Inline <script> tag found in $f"
              ERR=1
            fi
          done
          exit $ERR

      - name: "Ensure links use HTTPS"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            grep -Hn 'href="http://' "$f" && { echo "❌ Insecure HTTP link in $f"; ERR=1; }
          done
          exit $ERR

      - name: "Verify img alt attributes"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            grep -Hn '<img ' "$f" | while read -r line; do
              # if <img has no alt=
              if echo "$line" | grep -vq 'alt='; then
                echo "❌ Missing alt attribute: $line"
                ERR=1
              fi
            done
          done
          exit $ERR

      - name: "Detect inline event handlers"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            if grep -En 'on\w+=' "$f"; then
              echo "❌ Inline event handler found in $f"
              ERR=1
            fi
          done
          exit $ERR

      - name: "Summary"
        if: success()
        run: echo "✅ All basic HTML security checks passed!"
