name: "Basic Security Validation Workflow"

on:
  push:
    branches: ["main", "release/**"]
  pull_request:
    branches: ["main", "release/**"]
  workflow_dispatch:

jobs:
  html-security-checks:
    name: "HTML Security Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Check for inline <script> tags"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            if grep -q '<script>' "$f"; then
              echo "❌ Inline <script> tag found in $f"
              ERR=1
            fi
          done
          exit $ERR

      - name: "Ensure links use HTTPS"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            if grep -q 'href=\"http://' "$f"; then
              echo "❌ Insecure HTTP link in $f"
              ERR=1
            fi
          done
          exit $ERR

      - name: "Verify <img> tags have alt attributes"
        run: |
          ERR=0
          for f in $(find . -type f -name '*.html'); do
            grep -Hn '<img ' "$f" | while read -r line; do
              if echo "$line" | grep -vq 'alt='; then
                echo "❌ Missing alt attribute: $line"
                ERR=1
              fi
            done
          done
          exit $ERR

      - name: "Simulated Accessibility Test"
        run: |
          echo "Running accessibility mock tests..."
          echo "✔ Page titles present"
          echo "✔ Landmarks properly structured"
          echo "✔ Color contrast sufficient"
          sleep 1

      - name: "Simulated Lighthouse Performance Audit"
        run: |
          echo "Launching headless performance audit..."
          echo "📊 Simulated Lighthouse score: Performance 94, Accessibility 98, Best Practices 100, SEO 90"
          sleep 1

      - name: "Summary"
        run: echo "✅ All basic HTML and simulated tests passed!"
